# fly.toml app configuration file generated for speecher on 2023-12-06T23:35:30-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "speecher"
primary_region = "lax"

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/go"]

[env]
  PORT = "8080"
  AWS_REGION = "us-east-1"
  S3_BUCKET = "op1fun"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
